paginate/pageapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name ="pageapp"
urlpatterns = [
    path('', views.home, name='home'),
    path('<recherche>/', views.home ),
    path('<suivant>/', views.home ),
]

paginate/paginate/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pageapp.urls'))
]

paginate/pageapp/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    nom = models.CharField(max_length=250)
    prenom = models.CharField(max_length=250)
    tel = models.CharField(max_length=20)

paginate/pageapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *

# Create your views here.
def home(request):
    
    if request.POST :
        recherche = request.POST.get('rech')
        
        contacts = Contact.objects.all().filter(nom__icontains= recherche).order_by('nom')
    else:
        contacts = Contact.objects.all().order_by('nom')
        paginator = Paginator(contacts, 10)
        page = request.GET.get('page')
    try:
        contact = paginator.get_page(page)
    except EmptyPage:
        contact = paginator(1)
    except PageNotAnInteger:
        contact = paginator(paginator.num_pages)
    return render(request, 'index.html', {'contacts': contact})

paginate/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method='POST' action ="{% url 'pageapp:home' %}">
        {% csrf_token %}
        <input type="text" name='rech' id='rech'>
        <input type="submit" value='recherche'>
    </form>
    <table>
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Contact</th>
        </tr>
        {% if contacts|length > 0 %}
            {% for contact in contacts %}
                <tr>
                    <td>{{contact.nom|truncatewords:'2' }}</td>
                    <td>{{contact.prenom|truncatewords:'2'}}</td>
                    <td>{{contact.tel |truncatewords:'2'}}</td>                
                </tr>
            {% endfor %}
        {% endif %}
        
        
    </table>
    {% if contacts.has_previous %} 
        <a href="?page={{ contacts.previous_page_number }}">&lt; Previous</a>
    {% endif %}
    {% for i  in list_page  %}
    {% if forloop.counter <= 4 %}
        <a href="?page={{ i }}"><button>{{ i }}</button></a>
    {% endif %}
    {% endfor %}
    page {{contacts.number}} of {{contacts.paginator.num_pages}}
    {% if contacts.has_next %}
        <a href="?page={{ contacts.next_page_number }}">&gt; Next</a>
    {% endif %} 
    
</body>
</html>